name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
  push:
    branches:
      - "dev"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.KWIL_MACH_SECRET }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install dependencies
        env:
          GH_ACCESS_TOKEN: ${{ secrets.KWIL_MACH_SECRET }}
        run: |
          go version
          git config --global url."https://${GH_ACCESS_TOKEN}:x-oauth-basic@github.com/kwilteam/".insteadOf "https://github.com/kwilteam/"
          make download

      - name: Check tidiness of go.mod and go.sum
        run: |
          ./scripts/mods/check_tidy.sh

      - name: Ensure generated antlr is up-to-date
        run: |
          ./scripts/antlr/check_sync.sh

      - name: Run build
        run: |
          make build-go

      - name: Run unit test
        run: |
          make test